### ISSUE TITLE
Yap error running aleph script

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/SML-Bench#1]
Getting an error (missing libncurses.so.6) running the aleph script (on Debian 8) due to the provided Yap executable: 
```
$ ./run mutagenesis 42 res.txt
2016-03-16 12:00:41,652 Running learning task mutagenesis with learning problem 42
2016-03-16 12:00:41,658 Target dir is /tmp/tmp5dy5Zd
2016-03-16 12:00:41,933 Runnig Aleph
/home/user/SML-Bench/learningsystems/aleph/Linux-x86_64/yap: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "./run", line 216, in <module>
    output = subprocess.check_output([script_path], cwd=target_dir)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/tmp/tmp5dy5Zd/train.pl']' returned non-zero exit status 127
```

**Comment by SimonBin** [comment]
let's remove those for now...
